import streamlit as st
import pandas as pd
import numpy as np
import os
from datetime import datetime
import plotly.express as px
import plotly.graph_objects as go


from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

DATA_DIR = "data"
TRAIN_FILE = os.path.join(DATA_DIR, "online_fashion_churn_train.csv")
TEMPLATE_FILE = os.path.join(DATA_DIR, "online_fashion_customers_template.csv")

NUMERIC_FEATURES = [
    "age",
    "recency_days",
    "frequency_6m",
    "monetary_6m",
    "discount_sensitivity",
    "returns_rate",
    "cod_preference",
]

# -------------------- Page config & basic style --------------------
st.set_page_config(
    page_title="Online Fashion Churn Studio",
    layout="wide",
)

st.markdown(
    """
    <style>
    .block-container {
        padding-top: 1rem;
        padding-bottom: 1rem;
        max-width: 1300px;
    }
    .metric-card {
        padding: 1rem;
        border-radius: 0.75rem;
        background-color: #111827;
        border: 1px solid #1f2933;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# -------------------- Load demo/template & training data --------------------
@st.cache_data
def load_template():
    df = pd.read_csv(TEMPLATE_FILE)
    return df

@st.cache_resource
def train_churn_model():
    """Train a simple churn model on the synthetic training data."""
    df_train = pd.read_csv(TRAIN_FILE)

    X = df_train[NUMERIC_FEATURES]
    y = df_train["churn"]

    pipe = Pipeline(
        [
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(max_iter=500)),
        ]
    )

    pipe.fit(X, y)
    return pipe

template_df = load_template()
model = train_churn_model()

# -------------------- Sidebar --------------------
st.sidebar.title("Online Fashion Churn Studio")

st.sidebar.write(
    """
    1. Upload your customer Excel/CSV  
    2. Select a customer by name  
    3. View churn probability & suggested actions  
    """
)

# -------------------- Main layout --------------------
st.title("Online Fashion Churn Analysis – Indian Online Fashion Retail")

st.markdown(
    "Use this tool to analyse customer behaviour and identify **churn risk** for your online fashion customers in India."
)

# ---- Upload section ----
st.subheader("1. Upload customer file")

uploaded_file = st.file_uploader(
    "Upload an Excel (`.xlsx`) or CSV file with customer data.",
    type=["csv", "xlsx"],
)

with st.expander("Demo template (how your Excel/CSV should look)", expanded=True):
    st.write(
        "Your file should have at least these columns (no `churn` column needed):"
    )
    st.dataframe(template_df.head(1))

required_cols = list(template_df.columns)

def load_user_data(file):
    if file is None:
        return None
    fname = file.name.lower()
    if fname.endswith(".xlsx"):
        df = pd.read_excel(file)
    else:
        df = pd.read_csv(file)

    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        st.error(
            f"Your file is missing these required columns: {', '.join(missing)}"
        )
        return None

    # keep only required columns to avoid surprises
    return df[required_cols].copy()

user_df = load_user_data(uploaded_file)

if user_df is None:
    st.info(
        "Upload your own customer file above to get predictions, "
        "or use the template CSV generated by the data script."
    )
    st.stop()

# -------------------- Score churn probabilities --------------------
scored_df = user_df.copy()
X_user = scored_df[NUMERIC_FEATURES]
churn_probs = model.predict_proba(X_user)[:, 1]
scored_df["churn_prob"] = churn_probs

def bucket_risk(p):
    if p < 0.33:
        return "Low"
    elif p < 0.66:
        return "Medium"
    else:
        return "High"

scored_df["churn_risk"] = scored_df["churn_prob"].apply(bucket_risk)

# -------------------- High-level metrics --------------------
st.subheader("2. Portfolio overview")

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown('<div class="metric-card">', unsafe_allow_html=True)
    st.metric("Total customers", len(scored_df))
    st.markdown("</div>", unsafe_allow_html=True)

with col2:
    avg_churn = scored_df["churn_prob"].mean()
    st.markdown('<div class="metric-card">', unsafe_allow_html=True)
    st.metric("Average churn probability", f"{avg_churn:.2%}")
    st.markdown("</div>", unsafe_allow_html=True)

with col3:
    high_risk_share = (scored_df["churn_risk"] == "High").mean()
    st.markdown('<div class="metric-card">', unsafe_allow_html=True)
    st.metric("High-risk customers", f"{high_risk_share:.1%} of base")
    st.markdown("</div>", unsafe_allow_html=True)

# -------------------- Customer-level analysis --------------------
st.subheader("3. Customer-level churn & suggested actions")

left_col, right_col = st.columns([1, 2])

with left_col:
    st.markdown("##### Search customer by name")

    name_options = sorted(scored_df["customer_name"].astype(str).unique())
    selected_name = st.selectbox(
        "Customer name", options=name_options, index=0
    )

    cust_row = scored_df[scored_df["customer_name"] == selected_name].iloc[0]

    st.markdown("##### Key behaviour (last 6 months)")
    st.write(
        f"- **Customer ID:** {cust_row['customer_id']}\n"
        f"- **City / State:** {cust_row['city']}, {cust_row['state']}\n"
        f"- **Preferred platform:** {cust_row['platform']}\n"
        f"- **Favourite brand / category:** {cust_row['fav_brand']} – {cust_row['fav_category']}\n"
        f"- **Recency:** {cust_row['recency_days']} days since last purchase\n"
        f"- **Frequency:** {cust_row['frequency_6m']} orders\n"
        f"- **Monetary:** ₹{cust_row['monetary_6m']:.0f} spent\n"
        f"- **Returns rate:** {cust_row['returns_rate']:.2f}\n"
    )

    prob = cust_row["churn_prob"]
    risk = cust_row["churn_risk"]

    st.markdown("##### Churn prediction")
    st.metric("Churn probability", f"{prob:.1%}", help="Probability that this customer will stop buying in the next period.")
    st.write(f"**Risk bucket:** {risk}")

    # Suggested actions
    st.markdown("##### Suggested actions")

    suggestions = []
    if risk == "High":
        suggestions.append("Run a **win-back campaign** with a strong personalised offer (e.g., 20–30% off on their favourite category).")
        suggestions.append("Send **curated product recommendations** based on their favourite brand and category.")
        suggestions.append("If COD preference is high, consider **limited-time free delivery** / COD fee waiver.")
    elif risk == "Medium":
        suggestions.append("Send a **gentle nudging campaign** – reminder of wishlist / recently viewed items.")
        suggestions.append("Offer **small loyalty points** or free shipping on the next purchase.")
    else:  # Low
        suggestions.append("Add them to a **loyalty / VIP programme** with early access to new drops.")
        suggestions.append("Encourage **cross-sell** into adjacent categories (e.g., footwear + accessories).")

    if cust_row["discount_sensitivity"] == 2:
        suggestions.append("This customer is **highly discount-sensitive** – structure offers with visible savings instead of subtle perks.")

    if cust_row["returns_rate"] > 0.3:
        suggestions.append("Monitor **high returns behaviour** – check fit/size issues and improve product recommendations.")

    for s in suggestions:
        st.write("• " + s)

with right_col:
    st.markdown("##### Where does this customer sit vs others?")

    # 1) Build dataframe for base scatter WITHOUT the selected customer
    plot_df = scored_df.copy()
    if selected_name:
        plot_df = plot_df[plot_df["customer_name"] != selected_name]

    # 2) Base scatter: all other customers
    fig = px.scatter(
        plot_df,
        x="recency_days",
        y="monetary_6m",
        color="churn_risk",  # "Low", "Medium", "High"
        hover_data=[
            "customer_id",
            "customer_name",
            "city",
            "fav_brand",
            "fav_category",
        ],
        labels={
            "recency_days": "Recency (days since last purchase)",
            "monetary_6m": "Monetary (₹ spent in last 6 months)",
        },
        title="Customer base: recency vs spend (colored by churn risk)",
        template="plotly_dark",
    )

    # Make base points smaller + semi-transparent
    fig.update_traces(
        marker=dict(size=5, opacity=0.35),
        selector=dict(mode="markers"),
    )

    # 3) Add legend entry + star annotation for the selected customer
    if selected_name:
        sel = scored_df[scored_df["customer_name"] == selected_name]
        if not sel.empty:
            row = sel.iloc[0]

            # (A) Dummy trace just for the legend (shows star icon)
            fig.add_trace(
                go.Scatter(
                    x=[row["recency_days"]],
                    y=[row["monetary_6m"]],
                    mode="markers",
                    name="Selected customer",
                    marker=dict(
                        symbol="star",
                        size=14,
                        color="gold",
                        line=dict(width=2, color="white"),
                        opacity=0.0,           # invisible on plot
                    ),
                    showlegend=True,
                    hoverinfo="skip",
                )
            )

            # (B) Big visible star as annotation – ALWAYS on top of everything
            fig.add_annotation(
                x=row["recency_days"],
                y=row["monetary_6m"],
                text="⭐",
                showarrow=False,
                font=dict(size=28),
                xanchor="center",
                yanchor="middle",
            )

    # 4) Layout tidy-up
    fig.update_layout(
        legend_title_text="Churn risk",
        legend=dict(
            bgcolor="rgba(0,0,0,0)",
            borderwidth=0,
        ),
        height=430,
        margin=dict(l=10, r=10, t=40, b=10),
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
    )

    st.plotly_chart(fig, use_container_width=True)


# -------------------- Optional: show scored table --------------------
with st.expander("See scored customer table"):
    st.dataframe(
        scored_df[
            [
                "customer_id",
                "customer_name",
                "city",
                "platform",
                "fav_brand",
                "recency_days",
                "frequency_6m",
                "monetary_6m",
                "churn_prob",
                "churn_risk",
            ]
        ].sort_values("churn_prob", ascending=False)
    )
